EXEMPLO SENSOR DE LUZ CONECTADO A ESP8266

https://esphome.io/components/sensor/adc.html

# Sensor de luz
sensor:
  - platform: adc
    pin: A0
    id: 'LDR_1'
    name: "ESP8266 WEMOS Luz"
    update_interval: 10s
    filters:
      - multiply: 3.3
